version: 0.2

env:
  exported-variables:
    - DEPLOY_ENV

phases:
  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://backend.yml

  build:
    commands:
      - |
        echo "BRANCH_NAME=$BRANCH_NAME"
        if [[ "$BRANCH_NAME" == main* ]]; then
          export DEPLOY_ENV="stage"
        elif [[ "$BRANCH_NAME" == feature* ]]; then
          export DEPLOY_ENV="dev"
        else
          echo "Error: BRANCH_NAME must start with 'main' or 'feature'."
          exit 1
        fi
        echo "DEPLOY_ENV=$DEPLOY_ENV"
        
        aws cloudformation deploy \
          --template-file backend.yml \
          --stack-name BaseInfraStack-$DEPLOY_ENV \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --parameter-overrides Environment=$DEPLOY_ENV \
          --no-fail-on-empty-changeset
        
        aws cloudformation wait stack-create-complete --stack-name BaseInfraStack-$DEPLOY_ENV

  post_build:
    commands:
      - aws cloudformation describe-stacks --stack-name BaseInfraStack-$DEPLOY_ENV